print("Meu nome é Carlos.")
print("Hoje comecei minha jornada na programação.")
print("Projeto Atlas🚀")            
print("projeto-atlas - Primeiro Commit")
print("Texte de conecção GitHub")
print("Estou construindo o Projeto Atlas")